### ISSUE TITLE
The message is not sent when the telegram app is installed on the device.

### ISSUE THREAD

**Issue by orlandev** [UsamaSarwar/flutter#2]
I tested the library on a mobile device with Android 12 and once the process of sending the message is executed, the browser opens and immediately opens the app directly in the contact but does not send the message; neither does it add it in the telegram TextField for sending messages.

**Comment by UsamaSarwar** [comment]
Kindly provide the code snippet that is causing the error.

**Comment by WhyAnge1** [comment]
Same for me. Just tested on Android 13 real device. Telegram.send(username: "username", message: "Hi") redirects to _"t.me/username?text=Hi"_ that opens correct chat, but without message.

**Comment by UsamaSarwar** [comment]
> Same for me. Just tested on Android 13 real device. Telegram.send(username: "username", message: "Hi") redirects to _"t.me/username?text=Hi"_ that opens correct chat, but without message.

Can you please let me know which flutter version you are using?
You may send here the output of "flutter doctor -v"

**Comment by UsamaSarwar** [comment]
Hey @orlandev & @WhyAnge1,  

This issue has been fixed in the latest version! 🎉 Previously, the `t.me/username?text=message` URL worked inconsistently on some Android versions, causing the message not to appear in the Telegram chat.  

### 🔥 What's New?  
- **Native Deep Linking Support**: Now, the package uses Telegram’s `tg://msg` deep link when the app is installed, ensuring the message is pre-filled in the chat.  
- **Automatic Fallback**: If the app is not installed, it will open in the browser as before.  

### ✅ Fix Example  
Update to the latest version and try this:  

```dart
Telegram.send(
  username: "UsamaSarwar",
  message: "Hello, this is now working!"
);
```  

Let me know if you face any issues! 🚀
